# Generated by Django 5.1.1 on 2024-09-06 11:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_alter_product_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='descriptionLv',
        ),
        migrations.RemoveField(
            model_name='product',
            name='nameLv',
        ),
    ]
