# Generated by Django 5.1.1 on 2024-09-07 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_remove_product_descriptionlv_remove_product_namelv'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='название компании', max_length=255)),
                ('phone_number', models.CharField(help_text='номер телефона', max_length=20)),
                ('email', models.EmailField(help_text='gmail почта', max_length=254)),
                ('telegram_link', models.URLField(blank=True, help_text='ссылка на контакт в телеграм', null=True)),
                ('youtube_link', models.URLField(blank=True, help_text='ссылка на ютуб канал', null=True)),
                ('whatsapp_link', models.URLField(blank=True, help_text='ссылка на контакт в ватсапп', null=True)),
                ('address', models.CharField(help_text='адрес компании', max_length=255)),
                ('about', models.TextField(help_text='О компании текст')),
                ('location_image', models.ImageField(blank=True, help_text='картинка города (где базируется компания)', null=True, upload_to='images/')),
            ],
        ),
    ]
