# Generated by Django 5.1.1 on 2024-09-07 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_company'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='about',
            field=models.TextField(default='О компании', help_text='О компании текст'),
        ),
        migrations.AlterField(
            model_name='company',
            name='address',
            field=models.CharField(default='Адрес компании', help_text='адрес компании', max_length=255),
        ),
        migrations.AlterField(
            model_name='company',
            name='email',
            field=models.EmailField(default='example@example.com', help_text='gmail почта', max_length=254),
        ),
        migrations.AlterField(
            model_name='company',
            name='location_image',
            field=models.ImageField(blank=True, default='default.jpg', help_text='картинка города (где базируется компания)', null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='company',
            name='name',
            field=models.CharField(default='Название компании', help_text='название компании', max_length=255),
        ),
        migrations.AlterField(
            model_name='company',
            name='phone_number',
            field=models.CharField(default='Номер телефона', help_text='номер телефона', max_length=20),
        ),
        migrations.AlterField(
            model_name='company',
            name='telegram_link',
            field=models.URLField(blank=True, default='', help_text='ссылка на контакт в телеграм', null=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='whatsapp_link',
            field=models.URLField(blank=True, default='', help_text='ссылка на контакт в ватсапп', null=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='youtube_link',
            field=models.URLField(blank=True, default='', help_text='ссылка на ютуб канал', null=True),
        ),
    ]
