# Generated by Django 5.1.1 on 2024-09-07 10:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_alter_company_about_alter_company_address_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='company',
            options={'verbose_name': 'Компания', 'verbose_name_plural': 'Компания'},
        ),
    ]
