# Generated by Django 5.1.1 on 2024-09-07 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0011_company_intro_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='intro_img',
            field=models.ImageField(blank=True, default='images/intro.jpg', help_text='картинка города (где базируется компания)', upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='company',
            name='location_image',
            field=models.ImageField(blank=True, default='default.jpg', help_text='картинка города (где базируется компания)', upload_to='images/'),
        ),
    ]
