# Generated by Django 5.1.1 on 2024-09-07 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0016_alter_company_intro_img_alter_company_location_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='intro_img',
            field=models.ImageField(blank=True, default='images/intro.jpg', help_text='картинка города', null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='company',
            name='location_image',
            field=models.ImageField(blank=True, default='images/jurmala.jpg', help_text='картинка города', null=True, upload_to='images/'),
        ),
    ]
