# Generated by Django 5.1.1 on 2024-09-26 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0018_alter_company_intro_img_alter_company_location_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='discount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name='Скидка в процентах'),
        ),
        migrations.AddField(
            model_name='product',
            name='startPrice',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Начальная стоимость товара'),
        ),
    ]
