# Generated by Django 5.1.1 on 2024-09-26 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0019_product_discount_product_startprice'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='description_lv',
            field=models.TextField(default='Standarts teksts', verbose_name='Описание товара на латышском'),
        ),
        migrations.AddField(
            model_name='product',
            name='name_lv',
            field=models.CharField(default='Standarts nosaukums', max_length=255, verbose_name='Наименование товара на латышском'),
        ),
    ]
